#include "updatebehavior.h"
//
// Include your update_mySpecies header file here
//

UpdateBehavior *UpdateBehavior::create_updateBehavior(inds_stochastic **species, environment **habitat, int species_ID)
	{
	/*
	* A generic template for the code that updates the phenotypes of individuals during each time step. This is to be populated by code generated by the user.
	*/

   // test for species id
   // 	return new update_mySpecies(inds_object[species_id]);
	}

